# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac2a2877c24f297e4291a1b1300a41aef9e6ea50485fbae515e9e42cf9ceb6d4c4d6ef30e8d14922fefde0f09582173ee7cf25e08a4d858254bc9f7af3a56862

test:
  secret_key_base: 78da34e1172d828e4d4ea20052cbe8c36c22c28254dc57b2caa9b9123bb54dcfd3a509eb05acb2e351126882575d4fcb7989f6e1ca48936767c8ad2d7c502a1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
